### ISSUE TITLE
Filter out the author when dispatching reviewers

### ISSUE THREAD

**Issue by kerthcet** [kerthcet/github-workflow-as-kube#10]
```yaml
      - name: request for review
        run: |
          # request two reviewers from OWNERS file randomly
          PR_NUMBER=${{ github.event.pull_request.number }}
          REVIEWERS=$(yq '.reviewers[]' OWNERS | shuf | head -n 2 | paste -sd ",")
          gh pr edit $PR_NUMBER --add-reviewer $REVIEWERS
```

Right now, when dispatching reviewers, we'll not filter out the author if he's one of the reviewers, which may lead to only one reviewer requested.
